apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: USERINFO_DB_HOST
          value: {{ .Values.env.USERINFO_DB_HOST | quote }}
        - name: BILLING_DB_HOST
          value: {{ .Values.env.BILLING_DB_HOST | quote }}
        - name: USERINFO_DB_NAME
          value: {{ .Values.env.USERINFO_DB_NAME | quote }}
        - name: BILLING_DB_NAME
          value: {{ .Values.env.BILLING_DB_NAME | quote }}
        - name: BILLING_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: {{ .Values.secrets.BILLING_DB_USER }}
        - name: BILLING_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: {{ .Values.secrets.BILLING_DB_PASSWORD }}
        - name: USERINFO_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: {{ .Values.secrets.USERINFO_DB_USER }}
        - name: USERINFO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: {{ .Values.secrets.USERINFO_DB_PASSWORD }}
