apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGF0YWJhc2Vyb290cGFzc3dvcmQ=  # Base64 encoded: "databaserootpassword"
  MYSQL_USER: ZGF0YWJhc2V1c2Vy # Base64 encoded: "databaseuser"
  MYSQL_PASSWORD: ZGF0YWJhc2VwYXNzd29yZA== # Base64 encoded: "databasepassword"

# DO NOT COMMIT THIS!