apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGF0YWJhc2Vyb290cGFzc3dvcmQ=  # Base64 encoded: "databaserootpassword"
  MYSQL_USER: ZGF0YWJhc2VCaWxsaW5nVXNlcg== # Base64 encoded: "databaseBillingUser"
  MYSQL_PASSWORD: ZGF0YWJhc2VCaWxsaW5nUGFzc3dvcmQ= # Base64 encoded: "databaseBillingPassword"

# DO NOT COMMIT THIS!