apiVersion: v1
kind: Service
metadata:
  name: group3-hello-world-service
  labels:
    app: group3-hello-world
spec:
  type: NodePort
  selector:
    app: group3-hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
